/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import datastructures.User;
import java.awt.Color;

/**
 *
 * @author gudmu
 */
public class LoginView extends javax.swing.JPanel {
    private final Main parent;          //Parent JFrame

    /**
     * Creates new form loginView
     * @param main
     */
    public LoginView(Main main) {
        initComponents();
        this.parent = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsernameTextField = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLogin = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jGoToSearchView = new javax.swing.JButton();
        kennitala = new javax.swing.JLabel();
        jKennitalaTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jUsernameTextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameTextFieldActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        username.setText("Notendanafn");

        password.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        password.setText("Lykilorð");

        jLogin.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLogin.setText("Nýskráning");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });

        jPassword.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        jGoToSearchView.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jGoToSearchView.setText("<-");
        jGoToSearchView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGoToSearchViewActionPerformed(evt);
            }
        });

        kennitala.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        kennitala.setText("Kennitala");

        jKennitalaTextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jKennitalaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKennitalaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLogin)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(password)
                                .addGap(18, 18, 18)
                                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jGoToSearchView, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(username)
                            .addComponent(kennitala))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jKennitalaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGoToSearchView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kennitala)
                    .addComponent(jKennitalaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(18, 18, 18)
                .addComponent(jLogin)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameTextFieldActionPerformed

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        boolean nameValidated = validateName();
        boolean ssnValidated = validateSSN();
        boolean passwordValidated = validatePassword();
        
        if (!nameValidated || !ssnValidated || !passwordValidated) return;        
        
        String usernameInput = jUsernameTextField.getText();
        char[] passwordInput = jPassword.getPassword();
        String ssnInput = jKennitalaTextField.getText();
        
        User newUser = new User(ssnInput, usernameInput, new String(passwordInput));
        System.out.println(usernameInput);
        System.out.println(passwordInput);
        System.out.println(ssnInput);
    }//GEN-LAST:event_jLoginActionPerformed

    private void jGoToSearchViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGoToSearchViewActionPerformed
        this.parent.loadSearchView();
    }//GEN-LAST:event_jGoToSearchViewActionPerformed

    private void jKennitalaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKennitalaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKennitalaTextFieldActionPerformed

    /**
     * Skoðar hvort nafn sé gilt.
     * @return 
     */
    private boolean validateName() {
        boolean validated = jUsernameTextField.getText().length() > 2;
        if(!validated) jUsernameTextField.setBackground(new Color(1, 0, 0, 0.2f));
        else jUsernameTextField.setBackground(new Color(255, 255, 255));
        return validated; 
    }
    
     /**
     * Skoðar hvort Password sé gilt.
     * @return 
     */
    private boolean validatePassword() {
        boolean validated = jPassword.getPassword().length > 5;
        if (!validated) jPassword.setBackground(new Color(1, 0, 0, 0.2f));
        else jPassword.setBackground(new Color(255, 255, 255));
        return validated;
    } 
    
    /**
     * Skoðar hvort SSN sé gilt.
     * @return 
     */
    private boolean validateSSN() {
        String regex = "[0-9]{6}-[0-9]{4}";
        boolean matches = jKennitalaTextField.getText().matches(regex);
        if(!matches) jKennitalaTextField.setBackground(new Color(1, 0, 0, 0.2f));
        else jKennitalaTextField.setBackground(new Color(255, 255, 255));
        return matches;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jGoToSearchView;
    private javax.swing.JTextField jKennitalaTextField;
    private javax.swing.JButton jLogin;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsernameTextField;
    private javax.swing.JLabel kennitala;
    private javax.swing.JLabel password;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
