/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.Bookings;
import database.DatabaseQueries;
import datastructures.Booking;
import datastructures.Flight;
import datastructures.User;
import java.awt.BorderLayout;
import javax.swing.JTable;
import utils.Utilities;
import java.util.ArrayList;


/**
 *
 * @author gudmu
 */
public class MyBookingsView extends javax.swing.JPanel {
    private final Main parent;          //Parent JFrame
    private Flight flight;
    private String prevOn;
    private User loggedUser;
    private JTable currentTable;                //Current table holding searched flights
    private ArrayList<Booking> myBookings;
    /**
     * Creates new form MyBookingsView
     * @param main
     * @param flight
     * @param prevOn
     */
    public MyBookingsView(Main main, Flight flight, String prevOn) {
        initComponents();
        this.parent = main;
        this.flight = flight;
        this.prevOn = prevOn;
        this.myBookings = new ArrayList<>();
        loggedUser = this.parent.getLoggedInUser();
    }
    
    public void setPrevOn(String prevOn) {
        this.prevOn = prevOn;
    }
    
    public void setCurrentFlight(Flight flight) {
        this.flight = flight;
    }
    
    public void setLoggedInUser(User user) {
        this.loggedUser = user;
    }
    /**
     * uppfærir bókanir notanda
     * @param bookings 
     */
    public void updateMyBookings(Bookings bookings) {
        if (bookings == null) {
            this.myBookings = new ArrayList<>();
        } else {
            System.out.println(loggedUser);
            myBookings = DatabaseQueries.getUserBookings(parent.getLoggedInUser().getSsn());
        }
    }
    

    /**
     * Setur viðeigandi haus
     */
    public void setHeader(){
        renderTable();
        if (loggedUser == null) {
            jHeader.setText("Enginn notandi er skráður inn");
            return;
        }
        jHeader.setText("Notandi: " + loggedUser.getName());
    }
    
    /**
     * Renders table of flights onto jTableContainer
     */
    private void renderTable() {
        if (currentTable != null) {
            jTableContainer.remove(currentTable.getTableHeader());
            jTableContainer.remove(currentTable);
        }
        
        ArrayList<Booking> listBookings = myBookings;

        currentTable = Utilities.tableFromBookings(myBookings);
        jTableContainer.add(currentTable.getTableHeader(), BorderLayout.NORTH);
        jTableContainer.add(currentTable, BorderLayout.CENTER);
        this.revalidate();
    }
        
    /**
     * 
     */
    private void goToPrevPanel() {
        switch (prevOn) {
            case "booking":
                this.parent.loadBookingsView(flight);
                break;
            case "info":
                this.parent.loadFlightInfoView(flight);
                break;
            default:
                this.parent.loadSearchView();
                break;
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        jGoToPrevPanel = new javax.swing.JButton();
        jTableContainerScroll = new javax.swing.JScrollPane();
        jTableContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jHeader.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jGoToPrevPanel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jGoToPrevPanel.setText("<-");
        jGoToPrevPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGoToPrevPanelActionPerformed(evt);
            }
        });

        jTableContainerScroll.setBackground(new java.awt.Color(255, 255, 255));
        jTableContainerScroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableContainerScroll.setMaximumSize(new java.awt.Dimension(780, 400));
        jTableContainerScroll.setMinimumSize(new java.awt.Dimension(780, 400));

        jTableContainer.setBackground(new java.awt.Color(255, 255, 255));
        jTableContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableContainer.setAutoscrolls(true);
        jTableContainer.setLayout(new java.awt.BorderLayout());
        jTableContainerScroll.setViewportView(jTableContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jGoToPrevPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jTableContainerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGoToPrevPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHeader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jTableContainerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jGoToPrevPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGoToPrevPanelActionPerformed
        goToPrevPanel();
    }//GEN-LAST:event_jGoToPrevPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jGoToPrevPanel;
    private javax.swing.JLabel jHeader;
    private javax.swing.JPanel jTableContainer;
    private javax.swing.JScrollPane jTableContainerScroll;
    // End of variables declaration//GEN-END:variables
}
